version: "3.4"
services:
  webshop:
    container_name: webshop
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./:/app
